
jobs:
  test:
    docker:
      - image: mongo:latest
        ports:
          - '27017:27017'
      - image: redis:latest
        ports:
          - '6379:6379'
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
