jobs:
  test-deploy:
    docker:
      - image: 'circleci/node:14'
      - image: 'mongo:latest'
      - image: 'redis:latest'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:c1:82:ac:d3:ad:3c:73:22:f4:9b:8c:b4:2d:f5:6c"
      - checkout
      - run:
          name: Copy default config
          command: cp config/example-config.env config/config.env
      - run:
          name: Install packages
          command: npm ci --unsafe-perm
      - run:
          name: Test with npm
          command: npm test
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: connecting to devserver
          command: ssh -o StrictHostKeyChecking=no donategifts@dev.donate-gifts.com "echo $MONGO_URI >> config.test && echo NODE_ENV=development >> config.test && echo SESS_NAME=sid >> config.test &&          echo $SESS_SECRET >> config.test &&          echo SESS_LIFE=3600000 >> config.test &&          echo MAILGUN_API_KEY=onlyneededforproduction >> config.test &&          echo MAILGUN_DOMAIN=onlyneededforproduction >> config.test &&          echo USE_AWS=true >> config.test &&          echo $AWS_KEY >> config.test &&          echo $AWS_SECRET >> config.test &&          echo S3BUCKET=donategifts >> config.test &&          echo DEFAULT_EMAIL=no-reply@donate-gifts.com >> config.test &&          echo BASE_URL=https://dev.donate-gifts.com:8081 >> config.test &&          echo GOOGLE_CAPTCHA_KEY= >> config.test &&          echo LOCAL_DEVELOPMENT=false >> config.test &&          echo SOCKET_URL=wss://dev.donate-gifts.com >> config.test &&          echo $G_CLIENT_ID >> config.test &&          echo $FB_APP_ID >> config.test &&          echo $SLACK_INTEGRATION >> config.test &&          echo $SCRAPINGBEE_APIKEY >> config.test &&          echo WISHCARD_LOCK_IN_MINUTES=1 >> config.test"


version: 2.1
workflows:
  test_my_app:
    jobs:
      - test-deploy:
          filters:
            branches:
              only:
                - circleci-project-setup
