version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  docker:
    - image: mongo:latest
      ports:
        - '27017:27017'
    - image: redis:latest
      ports:
        - '6379:6379'
  node-tests:
    jobs:
      - node/test

