jobs:
  test:
    docker:
      - image: 'circleci/node:14'
      - image: 'mongo:latest'
      - image: 'redis:latest'
    steps:
      - checkout
      - run:
          name: Copy default config
          command: cp config/example-config.env config/config.env
      - run:
          name: Test with npm
          command: npm test

orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
