jobs:
  test-deploy:
    docker:
      - image: 'circleci/node:14'
      - image: 'mongo:latest'
      - image: 'redis:latest'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:c1:82:ac:d3:ad:3c:73:22:f4:9b:8c:b4:2d:f5:6c"
      - checkout
      - run:
          name: Copy default config
          command: cp config/example-config.env config/config.env
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Test with npm
          command: npm test
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: connecting to devserver
          command: ssh -o StrictHostKeyChecking=no donategifts@dev.donate-gifts.com "cd donategifts && rm -rf node-modules && git clean -qdfx && git reset --hard origin/master &&  pwd &&  cd config &&  echo \"$MONGODB\" > config.env &&  echo NODE_ENV=development >> config.env &&  echo SESS_NAME=sid >> config.env &&  echo $SESS_SECRET >> config.env &&  echo SESS_LIFE=3600000 >> config.env &&  echo MAILGUN_API_KEY=onlyneededforproduction >> config.env &&  echo MAILGUN_DOMAIN=onlyneededforproduction >> config.env &&  echo USE_AWS=true >> config.env &&  echo $AWS_KEY >> config.env &&  echo $AWS_SECRET >> config.env &&  echo S3BUCKET=donategifts >> config.env &&  echo DEFAULT_EMAIL=no-reply@donate-gifts.com >> config.env &&  echo BASE_URL=https://dev.donate-gifts.com:8081 >> config.env &&  echo GOOGLE_CAPTCHA_KEY= >> config.env &&  echo LOCAL_DEVELOPMENT=false >> config.env &&  echo SOCKET_URL=wss://dev.donate-gifts.com >> config.env &&  echo $G_CLIENT_ID >> config.env &&  echo $FB_APP_ID >> config.env &&  echo $SLACK_INTEGRATION >> config.env &&  echo $SCRAPINGBEE_APIKEY >> config.env &&  echo WISHCARD_LOCK_IN_MINUTES=1 >> config.env && npm ci && pm2 restart 0  "

version: 2.1
workflows:
  test_my_app:
    jobs:
      - test-deploy:
          filters:
            branches:
              only:
                - master
