jobs:
  test-deploy:
    docker:
      - image: 'circleci/node:14'
      - image: 'mongo:latest'
      - image: 'redis:latest'
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:c1:82:ac:d3:ad:3c:73:22:f4:9b:8c:b4:2d:f5:6c"
      - checkout
      - run:
          name: Copy default config
          command: cp config/example-config.env config/config.env
      - run:
          name: Install packages
          command: npm ci --unsafe-perm
      - run:
          name: Test with npm
          command: npm test
      - run:
          name: Check lint
          command: npm run lint
      - run:
          name: connecting to devserver
          command: ssh -o StrictHostKeyChecking=no donategifts@dev.donate-gifts.com "pwd && printf \"$MONGODB\" >> config.test && printf NODE_ENV=development >> config.test && printf SESS_NAME=sid >> config.test &&          printf $SESS_SECRET >> config.test &&          printf SESS_LIFE=3600000 >> config.test &&          printf MAILGUN_API_KEY=onlyneededforproduction >> config.test &&          printf MAILGUN_DOMAIN=onlyneededforproduction >> config.test &&          printf USE_AWS=true >> config.test &&          printf $AWS_KEY >> config.test &&          printf $AWS_SECRET >> config.test &&          printf S3BUCKET=donategifts >> config.test &&          printf DEFAULT_EMAIL=no-reply@donate-gifts.com >> config.test &&          printf BASE_URL=https://dev.donate-gifts.com:8081 >> config.test &&          printf GOOGLE_CAPTCHA_KEY= >> config.test &&          printf LOCAL_DEVELOPMENT=false >> config.test &&          printf SOCKET_URL=wss://dev.donate-gifts.com >> config.test &&          printf $G_CLIENT_ID >> config.test &&          printf $FB_APP_ID >> config.test &&          printf $SLACK_INTEGRATION >> config.test &&          printf $SCRAPINGBEE_APIKEY >> config.test &&          printf WISHCARD_LOCK_IN_MINUTES=1 >> config.test"


version: 2.1
workflows:
  test_my_app:
    jobs:
      - test-deploy:
          filters:
            branches:
              only:
                - circleci-project-setup
